tasks:
  - name: Dev Server
    init: |
      pnpm install
      pnpm run build
    command: |
      pnpm run dev

ports:
  - port: 5173
    name: Frontend
    onOpen: open-browser
    visibility: public
    description: "Svelte Frontend"
